import httpx
from datetime import datetime, timedelta, timezone
from fastapi import HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.repositories.credential_repo import CredentialRepository
from app.schemas.auth import (
    RegisterRequest,
    LoginRequest,
    AuthResponse,
    UserPublic,
    MessageResponse,
)
from app.security.hashing import hash_password, verify_password, needs_rehash
from app.core.config import get_settings

settings = get_settings()

class AuthService:
    """
    Auth-service business logic.

    Orchestration:
        register → user-service (create profile) → hash password → store credentials
        login → user-service (retrieve profile) → verify password → return tokens
        logout → invalidate session (session-service)

    HTTP calls to the user-service via httpx.
    Tokens will be generated by the token-service.
    Sessions will be managed by the session-service.
    """
    def __init__(self, db: AsyncSession):
        self.repo = CredentialRepository(db)

    # --- Internal calls to user service -----------------------------------------------------

    async def _create_user_profile(self, data: RegisterRequest) -> dict:
        """
        Creates the user profile via user-service.
        Returns the created profile as a dictionary.

        Raises:
            409 if email or username is already in use (forwards the user-service error)
            503 if user-service is unavailable
        """
        async with httpx.AsyncClient(timeout=10.0) as client:
            try:
                response = await client.post(
                    f"{settings.user_service_url}/users/",
                    json={
                        "email": data.email,
                        "username": data.username,
                        "password": data.password,
                        # The password is sent for rule validation
                        # in the user-service schema, but it will not be
                        # stored there — only the auth-service stores the hash
                    },
                )
            except httpx.ConnectError:
                raise HTTPException(
                    status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                    detail="User service is unavailable",
                )
            except httpx.TimeoutException:
                raise HTTPException(
                    status_code=status.HTTP_504_GATEWAY_TIMEOUT,
                    detail="User service timeout",
                )
        if response.status_code == status.HTTP_201_CREATED:
            return response.json()

        # Forward user-service errors (409, 422, etc.)
        raise HTTPException(
            status_code=response.status_code,
            detail=response.json().get("detail", "User creation failed"),
        )

    async def _get_user_by_email(self, email: str) -> dict:
        """
        Retrieves a user profile via email using a user service.
        Used during login.

        Raises:
            404 if the user does not exist
            503 if the user service is unavailable
        """
        async with httpx.AsyncClient(timeout=10.0) as client:
            try:
                response = await client.get(
                    f"{settings.user_service_url}/users/internal/by-email",
                    params={"email": email},
                )
            except httpx.ConnectError:
                raise HTTPException(
                    status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                    detail="User service is unavailable",
                )
            except httpx.TimeoutException:
                raise HTTPException(
                    status_code=status.HTTP_504_GATEWAY_TIMEOUT,
                    detail="User service timeout",
                )
        if response.status_code == status.HTTP_200_OK:
            return response.json()

        # 404 → unknown email → we say "invalid credentials" to avoid
        # revealing whether the email exists or not (security through obscurity)
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid email or password",
        )

    async def _get_user_by_id(self, user_id: str) -> dict:
        """Retrieves a user profile via id using a user service."""
        async with httpx.AsyncClient(timeout=10.0) as client:
            try:
                response = await client.get(
                    f"{settings.user_service_url}/users/{user_id}",
                )
            except httpx.ConnectError:
                raise HTTPException(
                    status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                    detail="User service is unavailable",
                )
            except httpx.TimeoutException:
                raise HTTPException(
                    status_code=status.HTTP_504_GATEWAY_TIMEOUT,
                    detail="User service timeout",
                )

        if response.status_code == status.HTTP_200_OK:
            return response.json()

        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found"
        )

    async def _delete_user_profile(self, user_id: str) -> None:
        """
        Deletes the user profile (best-effort rollback).
        Called if credential storage fails after profile creation.
        """
        async with httpx.AsyncClient(timeout=10.0) as client:
            try:
                await client.delete(
                    f"{settings.user_service_url}/users/{user_id}",
                )
            except Exception:
                # We log the failure but we don't retry —
                # The main transaction has already failed
                pass

    # --- Internal calls to token service -----------------------------------------------------

    async def _generate_tokens(self, user_id: str) -> dict:
        """
        Calls token-service to generate a token pair.
        Returns the TokenPairResponse dictionary.

        Reasons:
            503 if token-service is unavailable
        """
        async with httpx.AsyncClient(timeout=10.0) as client:
            try:
                response = await client.post(
                    f"{settings.token_service_url}/tokens/generate",
                    json={"user_id": user_id},
                )
            except httpx.ConnectError:
                raise HTTPException(
                    status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                    detail="Token service unavailable."
                )
            except httpx.TimeoutException:
                raise HTTPException(
                    status_code=status.HTTP_504_GATEWAY_TIMEOUT,
                    detail="Token service timeout",
                )

        if response.status_code == status.HTTP_200_OK:
            return response.json()

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to generate token.",
        )

    async def _revoke_access_token(self, access_token: str) -> None:
        """Revokes an access token via token-service (Redis blacklist)."""
        if not access_token or not access_token.strip():
            print("[_revoke_access_token] WARNING: empty access_token, skipping")
            return

        print(f"[_revoke_access_token] Call token-service: {settings.token_service_url}")
        print(f"[_revoke_access_token] Token: {access_token[:30]}...")

        async with httpx.AsyncClient(timeout=10.0) as client:
            try:
                response = await client.post(
                    f"{settings.token_service_url}/tokens/revoke",
                    json={"access_token": access_token},
                )
                if response.status_code == 200:
                    print("[_revoke_access_token] Token blacklisted successfully")
                else:
                    print(f"[_revoke_access_token] Unexpected status: {response.status_code}")
            except httpx.ConnectError:
                print("[_revoke_access_token] WARNING: token-service unavailable")
            except httpx.TimeoutException:
                print("[_revoke_access_token] WARNING: token-service timeout")
            except Exception as exc:
                print(f"[_revoke_access_token] WARNING: {exc}")

    # --- Internal calls to session service --------------------------------------------------

    async def _create_session(
            self,
            user_id: str,
            refresh_token_hash: str,
            device_info: str | None = None
    ) -> None:
        """Create a session in session service"""
        expires_at = datetime.now(timezone.utc) + timedelta(
            days=settings.refresh_token_expires_days
        )

        async with httpx.AsyncClient(timeout=10.0) as client:
            try:
                await client.post(
                    f"{settings.session_service_url}/sessions/create",
                    json={
                        "user_id": user_id,
                        "refresh_token_hash": refresh_token_hash,
                        "device_info": device_info,
                        "expires_at": expires_at.isoformat(),
                    }
                )
            except httpx.ConnectError:
                raise HTTPException(
                    status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                    detail="Session service unavailable",
                )
            except httpx.TimeoutException:
                raise HTTPException(
                    status_code=status.HTTP_504_GATEWAY_TIMEOUT,
                    detail="Session service timeout",
                )

    async def _revoke_session(self, refresh_token: str) -> None:
        """Revokes a session in session-service"""
        async with httpx.AsyncClient(timeout=10.0) as client:
            try:
                await client.post(
                    f"{settings.session_service_url}/sessions/revoke",
                    json={"refresh_token": refresh_token},
                )
            except Exception:
                pass

    async def _validate_session(
            self,
            refresh_token: str,
    ) -> dict:
        """Validates a refresh token via session-service."""
        async with httpx.AsyncClient(timeout=10.0) as client:
            try:
                response = await client.post(
                    f"{settings.session_service_url}/sessions/validate",
                    json={"refresh_token": refresh_token},
                )
            except httpx.ConnectError:
                raise HTTPException(
                    status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                    detail="Session service unavailable",
                )
            except httpx.TimeoutException:
                raise HTTPException(
                    status_code=status.HTTP_504_GATEWAY_TIMEOUT,
                    detail="Session service timeout",
                )
        return response.json()

    async def _rotate_session(self, old_refresh_token: str, new_refresh_token_hash: str) -> None:
        """Performs the refresh token rotation in session-service."""
        new_expires_at = datetime.now(timezone.utc) + timedelta(days=settings.refresh_token_expires_days)

        async with httpx.AsyncClient(timeout=10.0) as client:
            try:
                await client.post(
                    f"{settings.session_service_url}/sessions/rotate",
                    json={
                        "old_refresh_token": old_refresh_token,
                        "new_refresh_token_hash": new_refresh_token_hash,
                        "new_expires_at": new_expires_at.isoformat(),
                    }
                )
            except httpx.ConnectError:
                raise HTTPException(
                    status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                    detail="Session service unavailable",
                )
            except httpx.TimeoutException:
                raise HTTPException(
                    status_code=status.HTTP_504_GATEWAY_TIMEOUT,
                    detail="Session service timeout",
                )

    # --- Register ---------------------------------------------------------------------------

    async def register(self, data: RegisterRequest, device_info: str | None = None) -> AuthResponse:
        """
        Create a user account.

        Flow:
            1. Create the profile in user-service
            2. Hash the password with Argon2id
            3. Store the credential in identyx_auth (auth-service's database)
            4. Generate the tokens via token-service
            5. Create the session in session-service
            6. Return a complete AuthResponse

        If the credential fails after the profile is created,
        a profile rollback is attempted (best effort).
        """
        # Step 1 — Create the profile in user-service
        user_profile = await self._create_user_profile(data)
        user_id = user_profile["id"]

        # Step 2 — Hash the password
        hashed = hash_password(data.password)

        # Step 3 — Store the credential
        try:
            await self.repo.create(
                user_id=user_id,
                hashed_password=hashed,
            )
        except Exception:
            # Rollback best-effort: delete the created profile
            # to avoid a profile without credentials
            await self._delete_user_profile(user_id)
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Failed to store credentials. Please try again.",
            )

        # Step 4 — Call token-service
        tokens = await self._generate_tokens(user_id)

        # Step 5 — Create the session
        await self._create_session(
            user_id=user_id,
            refresh_token_hash=tokens["refresh_token_hash"],
            device_info=device_info,
        )

        # Step 6 — Return a complete AuthResponse
        return AuthResponse(
            access_token=tokens["access_token"],
            refresh_token=tokens["refresh_token"],
            token_type="Bearer",
            expires_in=tokens["expires_in"],
            user=UserPublic(
                id=user_profile["id"],
                email=user_profile["email"],
                username=user_profile["username"],
                is_verified=user_profile["is_verified"],
                avatar_url=user_profile["avatar_url"],
                avatar_provider=user_profile["avatar_provider"],
            ),
        )

    # --- Login ------------------------------------------------------------------------------

    async def login(self, data: LoginRequest, device_info: str | None = None) -> AuthResponse:
        """
        Logs a user.

        Flow:
            1. Retrieve the profile via user-service
            2. Retrieve the credential from identyx_auth (auth-service's database)
            3. Verify the password with Argon2id
            4. needs_rehash → silently update if necessary
            5. Generate the tokens via token-service
            6. Create the session in session-service
            7. Return a complete AuthResponse

        Security note:
            - The email address is not revealed (generic 401 response)
            - The timing is constant(Argon2id).
        """
        # Step 1 — Retrieve the profile
        user_profile = await self._get_user_by_email(data.email)
        user_id = user_profile["id"]

        # Step 2 — Retrieve the credential
        credential = await self.repo.get_by_user_id(user_id)
        if not credential:
            # Credential missing — should not occur in production
            # but we protect against inconsistent states
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid email or password",
            )

        # Step 3 — Verify the password
        if not verify_password(data.password, credential.hashed_password):
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid email or password",
            )

        # Step 4 — Update the hash if necessary
        # (Argon2 parameters changed in production)
        if needs_rehash(credential.hashed_password):
            new_hash = hash_password(data.password)
            await self.repo.update_password(
                user_id=user_id,
                new_hashed_password=new_hash,
            )

        # Step 5 — Call token-service
        tokens = await self._generate_tokens(user_id)

        # Step 6 — Create the session
        await self._create_session(
            user_id=user_id,
            refresh_token_hash=tokens["refresh_token_hash"],
            device_info=device_info,
        )

        # Step 7 — Return to full AuthResponse
        return AuthResponse(
            access_token=tokens["access_token"],
            refresh_token=tokens["refresh_token"],
            token_type="Bearer",
            expires_in=tokens["expires_in"],
            user=UserPublic(
                id=user_profile["id"],
                email=user_profile["email"],
                username=user_profile["username"],
                is_verified=user_profile["is_verified"],
                avatar_url=user_profile["avatar_url"],
                avatar_provider=user_profile["avatar_provider"],
            ),
        )

    # --- Logout -----------------------------------------------------------------------------

    async def logout(self, refresh_token: str, access_token: str | None = None) -> MessageResponse:
        """
        Disconnects a user.

        Flow:
            1. Revoke the session in session-service (refresh token)
            2. Revoke the access token in token-service (blacklist Redis)
                — best-effort, if access_token is provided

        The client must send the refresh_token.
        The access_token is optional — if provided,
        it is immediately blacklisted in Redis.
        """
        print(f"[logout] refresh_token: {refresh_token[:20]}...")
        print(f"[logout] access_token: {access_token[:20] if access_token else 'None'}")

        # Step 1 — Revoke the session
        await self._revoke_session(refresh_token)

        # Step 2 — Revoke the access token (best-effort)
        if access_token:
            await self._revoke_access_token(access_token)
        else:
            print("[service/logout] WARNING: absent access_token — token non-blacklisted")

        return MessageResponse(message="Successfully logged out")

    # --- Refresh ----------------------------------------------------------------------------

    async def refresh(self, refresh_token: str) -> AuthResponse:
        """
        Renew tokens with rotation.

        Flow:
            1. Validate the refresh token in the session service
            2. Retrieve the user profile via the user service
            3. Generate a new token pair via the token service
            4. Rotation in the session service:
                old hash replaced by new hash
            5. Return the AuthResponse with the new tokens

        Security:
            Each refresh token can only be used once.
            If an attacker uses a stolen token first,
            the legitimate user will receive a 401 error on the next refresh.
        """
        #Step 1 — Validate the session
        session_data = await self._validate_session(refresh_token)
        if not session_data.get("valid"):
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid or expired refresh token",
            )
        user_id = session_data["user_id"]

        # Step 2 — Retrieve the profile
        user_profile = await self._get_user_by_id(user_id)

        # Step 3 — Generate the new tokens
        tokens = await self._generate_tokens(user_id)

        # Step 4 — Session Rotation
        await self._rotate_session(
            old_refresh_token=refresh_token,
            new_refresh_token_hash=tokens["refresh_token_hash"],
        )

        # Step 5 — Return the new tokens
        return AuthResponse(
            access_token=tokens["access_token"],
            refresh_token=tokens["refresh_token"],
            token_type="Bearer",
            expires_in=tokens["expires_in"],
            user=UserPublic(
                id=user_profile["id"],
                email=user_profile["email"],
                username=user_profile["username"],
                is_verified=user_profile["is_verified"],
                avatar_url=user_profile["avatar_url"],
                avatar_provider=user_profile["avatar_provider"],
            )
        )