import httpx
from fastapi import HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.repositories.credential_repo import CredentialRepository
from app.schemas.auth import (
    RegisterRequest,
    LoginRequest,
    AuthResponse,
    UserPublic,
    MessageResponse,
)
from app.security.hashing import hash_password, verify_password, needs_rehash
from app.core.config import get_settings

settings = get_settings()

class AuthService:
    """
    Auth-service business logic.

    Orchestration:
        register → user-service (create profile) → hash password → store credentials
        login → user-service (retrieve profile) → verify password → return tokens
        logout → invalidate session (session-service)

    HTTP calls to the user-service via httpx.
    Tokens will be generated by the token-service.
    Sessions will be managed by the session-service.
    """
    def __init__(self, db: AsyncSession):
        self.repo = CredentialRepository(db)

    # --- Internal calls to user service -----------------------------------------------------

    async def _create_user_profile(self, data: RegisterRequest) -> dict:
        """
        Creates the user profile via user-service.
        Returns the created profile as a dictionary.

        Raises:
            409 if email or username is already in use (forwards the user-service error)
            503 if user-service is unavailable
        """
        async with httpx.AsyncClient(timeout=10.0) as client:
            try:
                response = await client.post(
                    f"{settings.user_service_url}/users/",
                    json={
                        "email": data.email,
                        "username": data.username,
                        "password": data.password,
                        # The password is sent for rule validation
                        # in the user-service schema, but it will not be
                        # stored there — only the auth-service stores the hash
                    },
                )
            except httpx.ConnectError:
                raise HTTPException(
                    status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                    detail="User service is unavailable",
                )
            except httpx.TimeoutException:
                raise HTTPException(
                    status_code=status.HTTP_504_GATEWAY_TIMEOUT,
                    detail="User service timeout",
                )
        if response.status_code == status.HTTP_201_CREATED:
            return response.json()

        # Forward user-service errors (409, 422, etc.)
        raise HTTPException(
            status_code=response.status_code,
            detail=response.json().get("detail", "User creation failed"),
        )

    async def _get_user_by_email(self, email: str) -> dict:
        """
        Retrieves a user profile via email using a user service.
        Used during login.

        Raises:
            404 if the user does not exist
            503 if the user service is unavailable
        """
        async with httpx.AsyncClient(timeout=10.0) as client:
            try:
                response = await client.get(
                    f"{settings.user_service_url}/users/internal/by-email",
                    params={"email": email},
                )
            except httpx.ConnectError:
                raise HTTPException(
                    status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                    detail="User service is unavailable",
                )
            except httpx.TimeoutException:
                raise HTTPException(
                    status_code=status.HTTP_504_GATEWAY_TIMEOUT,
                    detail="User service timeout",
                )
        if response.status_code == status.HTTP_200_OK:
            return response.json()

        # 404 → unknown email → we say "invalid credentials" to avoid
        # revealing whether the email exists or not (security through obscurity)
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid email or password",
        )

    async def _delete_user_profile(self, user_id: str) -> None:
        """
        Deletes the user profile (best-effort rollback).
        Called if credential storage fails after profile creation.
        """
        async with httpx.AsyncClient(timeout=10.0) as client:
            try:
                await client.delete(
                    f"{settings.user_service_url}/users/{user_id}",
                )
            except Exception:
                # We log the failure but we don't retry —
                # The main transaction has already failed
                pass

    async def _generate_tokens(self, user_id: str) -> dict:
        """
        Calls token-service to generate a token pair.
        Returns the TokenPairResponse dictionary.

        Reasons:
            503 if token-service is unavailable
        """
        async with httpx.AsyncClient(timeout=10.0) as client:
            try:
                response = await client.post(
                    f"{settings.token_service_url}/tokens/generate",
                    json={"user_id": user_id},
                )
            except httpx.ConnectError:
                raise HTTPException(
                    status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                    detail="Token service unavailable."
                )
            except httpx.TimeoutException:
                raise HTTPException(
                    status_code=status.HTTP_504_GATEWAY_TIMEOUT,
                    detail="Token service timeout",
                )

        if response.status_code == status.HTTP_200_OK:
            return response.json()

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to generate token.",
        )

    # --- Register ---------------------------------------------------------------------------

    async def register(self, data: RegisterRequest) -> AuthResponse:
        """
        Create a user account.

        Flow:
            1. Create the profile in user-service (valid email + unique username)
            2. Hash the password with Argon2id
            3. Store the credential in identyx_auth (auth-service's database)
            4. Call token-service to generate the tokens
            5. Return to full AuthResponse

        If the credential fails after the profile is created,
        a profile rollback is attempted (best effort).
        """
        # Step 1 — Create the profile in user-service
        user_profile = await self._create_user_profile(data)
        user_id = user_profile["id"]

        # Step 2 — Hash the password
        hashed = hash_password(data.password)

        # Step 3 — Store the credential
        try:
            await self.repo.create(
                user_id=user_id,
                hashed_password=hashed,
            )
        except Exception:
            # Rollback best-effort: delete the created profile
            # to avoid a profile without credentials
            await self._delete_user_profile(user_id)
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Failed to store credential. Please try again.",
            )

        # Step 4 — Call token-service
        tokens = await self._generate_tokens(user_id)

        # Step 5 — Return to full AuthResponse
        return AuthResponse(
            access_token=tokens["access_token"],
            refresh_token=tokens["refresh_token"],
            token_type="Bearer",
            expires_in=tokens["expires_in"],
            user=UserPublic(
                id=user_profile["id"],
                email=user_profile["email"],
                username=user_profile["username"],
                is_verified=user_profile["is_verified"],
                avatar_url=user_profile["avatar_url"],
                avatar_provider=user_profile["avatar_provider"],
            ),
        )

    # --- Login ------------------------------------------------------------------------------

    async def login(self, data: LoginRequest) -> AuthResponse:
        """
        Logs a user.

        Flow:
            1. Retrieve the profile via user-service (by email)
            2. Retrieve the credential from identyx_auth (auth-service's database)
            3. Verify the password with Argon2id
            4. If needs_rehash → silently update the hash
            5. Call token-service to generate the tokens
            6. Return to full AuthResponse

        Security note:
            - The email address is not revealed (generic 401 response)
            - The timing is constant thanks to Argon2id.
        """
        # Step 1 — Retrieve the profile
        user_profile = await self._get_user_by_email(data.email)
        user_id = user_profile["id"]

        # Step 2 — Retrieve the credential
        credential = await self.repo.get_by_user_id(user_id)
        if not credential:
            # Credential missing — should not occur in production
            # but we protect against inconsistent states
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid email or password",
            )

        # Step 3 — Verify the password
        if not verify_password(data.password, credential.hashed_password):
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid email or password",
            )

        # Step 4 — Update the hash if necessary
        # (Argon2 parameters changed in production)
        if needs_rehash(credential.hashed_password):
            new_hash = hash_password(data.password)
            await self.repo.update_password(
                user_id=user_id,
                new_hashed_password=new_hash,
            )

        # Step 5 — Call token-service
        tokens = await self._generate_tokens(user_id)

        # Step 6 — Return to full AuthResponse
        return AuthResponse(
            access_token=tokens["access_token"],
            refresh_token=tokens["refresh_token"],
            token_type="Bearer",
            expires_in=tokens["expires_in"],
            user=UserPublic(
                id=user_profile["id"],
                email=user_profile["email"],
                username=user_profile["username"],
                is_verified=user_profile["is_verified"],
                avatar_url=user_profile["avatar_url"],
                avatar_provider=user_profile["avatar_provider"],
            ),
        )

    # --- Logout -----------------------------------------------------------------------------

    async def logout(self, refresh_token: str) -> MessageResponse:
        """
        Disconnects a user.

        token-service: clean placeholder.
        session-service: will invalidate the refresh token in session-service.
        token-service: will also revoke the access token via token-service.
        """
        # TODO call session-service to invalidate the token
        # TODO call token-service to revoke access
        return MessageResponse(message="Successfully logged out")

    # --- Refresh ----------------------------------------------------------------------------

    async def refresh(self, refresh_token: str) -> AuthResponse:
        """
        Renews tokens from a valid refresh token.

        auth-service: Placeholder 501.
        token-service: full implementation with session-service.

         Full implementation:
            1. Call the session-service to validate the refresh token (exists, not revoked, not expired)
            2. Call the token-service to generate a new access token
            3. Rotation: generate a new refresh token,
            invalidate the old one in the session-service
            4. Return the new tokens

        Rotation ensures that a stolen refresh token is unusable
        as soon as it has been used once.
        """
        # TODO implement with token-service + session-service
        raise HTTPException(
            status_code=status.HTTP_501_NOT_IMPLEMENTED,
            detail="Token refresh not implemented yet — coming soon.",
        )
