import re
import string

from pydantic import BaseModel, EmailStr, field_validator

USERNAME_MIN = 3
USERNAME_MAX = 50
USERNAME_PATTERN = re.compile(r"^[a-zA-Z0-9_-]+$")

class RegisterRequest(BaseModel):
    """
    Data for creating an account
    POST /auth/register
    """
    email: EmailStr
    username: str
    password: str

    @field_validator("email", mode="before")
    @classmethod
    def normalize_email(cls, validator) -> str:
        """Lowercase + strip the email so duplicates are impossible."""
        if isinstance(validator, str):
            return validator.strip().lower()
        return validator

    @field_validator("username")
    @classmethod
    def validate_username(cls, validator: str) -> str:
        my_validator = validator.strip()
        if not (USERNAME_MIN <= len(my_validator) <= USERNAME_MAX):
            raise ValueError(
                f"Username must be between {USERNAME_MIN} and {USERNAME_MAX} characters."
            )
        if not USERNAME_PATTERN.match(my_validator):
            raise ValueError(
                "Username can only contain letters, numbers, _ and - characters."
            )
        return my_validator

    @field_validator("password")
    @classmethod
    def validate_password(cls, validator: str) -> str:
        if (
            len(validator) < 8
            or not any(char.isupper() for char in validator)
            or not any(char.isdigit() for char in validator)
            or not any(char in string.punctuation for char in validator)
        ):
            raise ValueError(
                "Password must be at least 8 characters,"
                "with 1 uppercase, 1 digit and 1 punctuation."
            )
        return validator

class LoginRequest(BaseModel):
    """
    Data for logging in
    POST /auth/login
    """
    email: EmailStr
    password: str

class LogoutRequest(BaseModel):
    """
    Logout data.

    refresh_token: required — revokes the session in session-service.
    The access token is NOT sent in the body — it is extracted
    by the auth-service from the X-Access-Token header
    (injected by the gateway from the Authorization header).
    """
    refresh_token: str

class RefreshRequest(BaseModel):
    """
    Refresh token to be exchanged for a new access token.
    POST /auth/refresh
    Full implementation later (token service + session service).
    """
    refresh_token: str

class ResetPasswordRequest(BaseModel):
    """
    Sets a new password using a one-time reset token.
    POST /auth/reset-password

    token: HMAC-signed token received in the security email link.
    """
    token: str
    new_password: str

    @field_validator("new_password")
    @classmethod
    def validate_password(cls, validator: str) -> str:
        if (
            len(validator) < 8
            or not any(char.isupper() for char in validator)
            or not any(char.isdigit() for char in validator)
            or not any(char in string.punctuation for char in validator)
        ):
            raise ValueError(
                "Password must be at least 8 characters,"
                "with 1 uppercase, 1 digit and 1 punctuation."
            )
        return validator

class ResendVerificationRequest(BaseModel):
    """
    Requests a fresh verification email.
    POST /auth/resend-verification
    """
    email: EmailStr

class VerifyEmailResponse(BaseModel):
    """Response following email verification."""
    message: str
    email: str
    is_verified: bool

class UserPublic(BaseModel):
    """Public profile returned in AuthResponse"""
    id: str
    email: str
    username: str
    is_verified: bool
    avatar_url: str | None = None
    avatar_provider: str

class AuthResponse(BaseModel):
    """
    Response after successful registration or login.

    auth-service:
        - access_token and refresh_token are empty placeholders
        - They will be generated by the token-service

    token-service:
        - access_token: signed JWT (stateless)
        - refresh_token: hashed opaque token (stateful, stored in session-service)
    """
    access_token: str
    refresh_token: str
    token_type: str = "Bearer"
    expires_in: int         # seconds before access_token expiration
    user: UserPublic

class MessageResponse(BaseModel):
    """Simple response with a message"""
    message: str

class VerifyPasswordRequest(BaseModel):
    """
    Password confirmation for destructive operations (delete account,
    delete avatar). Called by the gateway (internal endpoint).
    """
    user_id: str
    password: str

class VerifyPasswordResponse(BaseModel):
    """Result of the password confirmation check."""
    valid: bool

class CreateDeletionRequestRequest(BaseModel):
    """
    Creates an account deletion confirmation request (GDPR).

    Called by the gateway after the password has been confirmed.
    auth-service generates an HMAC-signed token, stores it in
    user-service and triggers the confirmation email.
    """
    user_id: str

class ConfirmDeletionRequest(BaseModel):
    """
    Confirms a GDPR account deletion using the email token.

    token: HMAC-signed one-time token received in the deletion email link.
    """
    token: str

class DeletionRequestResponse(BaseModel):
    """Response after a deletion request has been created."""
    message: str

class EmailChangeRequest(BaseModel):
    """
    Requests an email address change.

    Called by the gateway after the password has been confirmed.
    auth-service generates an HMAC-signed token, stores it in
    user-service and triggers a confirmation email to the NEW address.
    """
    user_id: str
    new_email: EmailStr

    @field_validator("new_email", mode="before")
    @classmethod
    def normalize_email(cls, validator) -> str:
        """Lowercase + strip the email so duplicates are impossible."""
        if isinstance(validator, str):
            return validator.strip().lower()
        return validator

class ConfirmEmailChangeRequest(BaseModel):
    """
    Confirms an email change using the one-time token.

    token: HMAC-signed one-time token received in the confirmation email
           sent to the NEW address.
    """
    token: str