import re
import string

from pydantic import BaseModel, EmailStr, field_validator

USERNAME_MIN = 3
USERNAME_MAX = 50
USERNAME_PATTERN = re.compile(r"^[a-zA-Z0-9_-]+$")

class RegisterRequest(BaseModel):
    """
    Data for creating an account
    POST /auth/register
    """
    email: EmailStr
    username: str
    password: str

    @field_validator("username")
    @classmethod
    def validate_username(cls, validator: str) -> str:
        my_validator = validator.strip()
        if not (USERNAME_MIN <= len(my_validator) <= USERNAME_MAX):
            raise ValueError(
                f"Username must be between {USERNAME_MIN} and {USERNAME_MAX} characters."
            )
        if not USERNAME_PATTERN.match(my_validator):
            raise ValueError(
                "Username can only contain letters, numbers, _ and - characters."
            )
        return my_validator

    @field_validator("password")
    @classmethod
    def validate_password(cls, validator: str) -> str:
        if (
            len(validator) < 8
            or not any(char.isupper() for char in validator)
            or not any(char.isdigit() for char in validator)
            or not any(char in string.punctuation for char in validator)
        ):
            raise ValueError(
                "Password must be at least 8 characters,"
                "with 1 uppercase, 1 digit and 1 punctuation."
            )
        return validator

class LoginRequest(BaseModel):
    """
    Data for logging in
    POST /auth/login
    """
    email: EmailStr
    password: str

class LogoutRequest(BaseModel):
    """
    Logout data.

    refresh_token: required — revokes the session in session-service
    access_token: optional — immediately revokes the access token
                  in Redis via token-service.
    """
    refresh_token: str
    access_token: str | None = None

class RefreshRequest(BaseModel):
    """
    Refresh token to be exchanged for a new access token.
    POST /auth/refresh
    Full implementation later (token service + session service).
    """
    refresh_token: str

class UserPublic(BaseModel):
    """Public profile returned in AuthResponse"""
    id: str
    email: str
    username: str
    is_verified: bool
    avatar_url: str
    avatar_provider: str

class AuthResponse(BaseModel):
    """
    Response after successful registration or login.

    auth-service:
        - access_token and refresh_token are empty placeholders
        - They will be generated by the token-service

    token-service:
        - access_token: signed JWT (stateless)
        - refresh_token: hashed opaque token (stateful, stored in session-service)
    """
    access_token: str
    refresh_token: str
    token_type: str = "Bearer"
    expires_in: int         # seconds before access_token expiration
    user: UserPublic

class MessageResponse(BaseModel):
    """Simple response with a message"""
    message: str